default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  database: first_app_development
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  <<: *default
  adapter: mysql2
  database: first_app_test
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>